### ISSUE TITLE
how to implement this ?

### ISSUE THREAD

**Issue by feydreva** [arch4edu/aur-auto-update#41]
Hello, 
I am really interested in this.
I maintain an AUR package.
I got nvcheker working, so I get a notification when a new version is there.
But I need to manually update the PKGBUILD and manually git push to aur.

I would love to have a bot doing version update automatically, but reading this, I don't understand how to implement it.
Could you guide me with more instruction ?

Thank you

**Comment by carlosal1015** [comment]
Nice @feydreva , first step is add as comaintaner the user `AutoUpdateBot` like this
![image](https://github.com/arch4edu/aur-auto-update/assets/21283014/774f86bf-3e9f-4d32-89d5-af6c05db57b9)

Then, submite a pull request and create a file over `config/feydreva/<package-name>.yaml` for example, here you can share your nvchecker entry to help to modify. For example

```
nvchecker:
  gitlab: libxc/libxc
  source: gitlab
  use_max_tag: true
test: true
```

**Comment by feydreva** [comment]
Hello, 
So after some effort, lots of reading about git and how it works, I made a pull request.
please be kind :)
if there is any mistake or other things I need to do, let me know !
Thank you for your help and patience

**Comment by carlosal1015** [comment]
Thanks, let's run the pipeline for the PR #42

**Comment by feydreva** [comment]
Hello, 
Autobot doesn't seem to update the package with new version.
Is there anything I have to do ? how can I verify this ?
Thank you

**Comment by carlosal1015** [comment]
True, `winamax-bin.yaml` needs `python-lxml` in order to support for htmlparser.
Many nvchecker configs here using regex like this
```
nvchecker:
  regex: pkgname-([\d.]+).tar.gz
  source: regex
  url: https://www.example.com
pkgver: get-pkgver
test:
  enable: true
```
We can switch to regex instead of xml parser.

**Comment by petronny** [comment]
>Autobot doesn't seem to update the package with new version.

https://github.com/arch4edu/aur-auto-update/actions/runs/8306337444/job/22734274209
```
 ModuleNotFoundError: No module named 'typing_extensions'
Error: Process completed with exit code 1.
```
This workflow is failing. Fixing now.

**Comment by petronny** [comment]
In https://github.com/arch4edu/aur-auto-update/actions/runs/8308392492/job/22738576498
```
 [I 03-16 14:21:15.467 core:374] winamax-bin: updated to 0;url=https://dl.winamax.fr/client/electron/linux/all/winamax-1.53.0.deb
```
```
No action is configured for winamax-bin.
```
Please check the parsed version. When the version is correct, set `test: true` to enable the build test.

**Comment by feydreva** [comment]
hmm trying to make a new config file, but do not succeed to make it work :/
This only place I see the name of the file is in the source code of the page : 
<meta http-equiv="refresh" content="0;url=https://dl.winamax.fr/client/electron/linux/all/winamax-1.53.0.deb">
regex doesn't seem to work here

**Comment by carlosal1015** [comment]
No worries, if you have some progress, we could take a look.

**Comment by petronny** [comment]
There is another problem. The page is hosted on cloudfront and could not be accessed from some country/region.
So it may return 403 sometime in GitHub Actions.

> This only place I see the name of the file is in the source code of the page :
regex doesn't seem to work here

regex will work here.
```yaml
nvchecker:
  source: "regex"
  url: "https://www.winamax.fr/jouer-au-poker?dl=1&platform=linux"
  regex: 'winamax-([\d.]+).deb'
```
